package org.tridefense.android.integration

import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder

/** MOCK fixture configuration supplied by the local test operator, never generated by Android AI. */
data class MockFixture(val backendUrl: String, val registryAddress: String, val request: JSONObject) {
    companion object {
        fun parse(text: String): MockFixture {
            require(text.length <= 150_000) { "Fixture is too large" }
            val json = JSONObject(text)
            require(json.getString("proofMode") == "MOCK_PROOF" && json.getString("chainId") == "31337")
            val endpoint = json.getString("backendUrl").trimEnd('/')
            val url = URL(endpoint)
            require(url.protocol == "http" && url.host in setOf("127.0.0.1", "localhost", "10.0.2.2") &&
                url.userInfo == null && url.path.isEmpty() && url.query == null && url.ref == null) {
                "Only local debug Backend URLs are supported"
            }
            val registry = json.getString("registryAddress")
            require(Regex("0x[0-9a-fA-F]{40}").matches(registry))
            val request = json.getJSONObject("submission")
            require(request.keys().asSequence().toSet() == setOf("idempotencyKey", "nonce", "voiceprintHash", "riskScore", "proof", "publicInputs"))
            require(request.getJSONArray("publicInputs").length() == 8)
            require(request.get("riskScore") is Int && request.getInt("riskScore") in 0..10000)
            require(Regex("0x[0-9a-fA-F]{64}").matches(request.getString("voiceprintHash")))
            require(Regex("0x(?:[0-9a-fA-F]{2})+").matches(request.getString("proof")))
            return MockFixture(endpoint, registry.lowercase(), request)
        }
    }
}

class BackendFailure(val code: String, val httpStatus: Int = 0) : Exception(code)

/** Real HTTP transport; no direct RPC, fixture admission, hash generation or proof verification. */
interface BackendTransport {
    fun request(path: String, body: JSONObject? = null): JSONObject
}

class HttpBackendClient(private val fixture: MockFixture) : BackendTransport {
    override fun request(path: String, body: JSONObject?): JSONObject {
        require(path.startsWith("/v1/"))
        val connection = URL(fixture.backendUrl + path).openConnection() as HttpURLConnection
        try {
            connection.connectTimeout = 5000
            connection.readTimeout = 10000
            connection.instanceFollowRedirects = false
            connection.requestMethod = if (body == null) "GET" else "POST"
            if (body != null) {
                connection.doOutput = true
                connection.setRequestProperty("Content-Type", "application/json")
                connection.outputStream.use { it.write(body.toString().toByteArray(Charsets.UTF_8)) }
            }
            val status = connection.responseCode
            val stream = if (status in 200..299) connection.inputStream else connection.errorStream
            val text = stream?.bufferedReader()?.use { it.readText() } ?: throw BackendFailure("EMPTY_RESPONSE", status)
            val json = JSONObject(text)
            if (status !in 200..299) throw BackendFailure(json.optString("errorCode", "HTTP_$status"), status)
            require(json.getString("chainId") == "31337" && json.getString("proofMode") == "MOCK_PROOF" &&
                json.getString("registryAddress").lowercase() == fixture.registryAddress) { "Unexpected Backend domain or proof mode" }
            return json
        } finally { connection.disconnect() }
    }
}

internal fun encoded(value: String): String = URLEncoder.encode(value, "UTF-8")
